FROM debian:11.9-slim

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
        supervisor \
        nginx \
        php-fpm \
        php-apcu \
        php-bz2 \
        php-curl \
        php-gd \
        php-json \
        php-mbstring \
        php-mysql \
        php-opcache \
        php-readline \
        php-sqlite3 \
        php-zip \
        && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /run/php

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY default /etc/nginx/sites-available/default

CMD ["/usr/bin/supervisord"]
