FROM debian:11.9-slim

RUN apt-get update && \
    apt-get install -y \
        supervisor \
        nginx \
        php-fpm

RUN mkdir -p /run/php

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

CMD ["/usr/bin/supervisord"]
