app = 'denny-nginx-php-base'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile.php-7.4'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
